version: '3'
services:
  pcfSQL:
    container_name: build-db-local
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - mssql-server-data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd1!
    ports:
      - '1433:1433'
volumes:
  mssql-server-data:
